// PRODUCER CONSTANTS
export const DATABASE_CONNECTION_REPOSITORY = 'DATABASE_CONNECTION_REPOSITORY';
export const CREATE_PRODUCER_USE_CASE = 'CREATE_PRODUCER_USE_CASE';
export const CREATE_PRODUCER_SERVICE = 'CREATE_PRODUCER_SERVICE';
export const UPDATE_PRODUCER_USE_CASE = 'UPDATE_PRODUCER_USE_CASE';
export const UPDATE_PRODUCER_SERVICE = 'UPDATE_PRODUCER_SERVICE';
export const DELETE_PRODUCER_USE_CASE = 'DELETE_PRODUCER_USE_CASE';
export const DELETE_PRODUCER_SERVICE = 'DELETE_PRODUCER_SERVICE';
export const LIST_PRODUCER_BY_CPF_CNPJ_USE_CASE = 'LIST_PRODUCER_BY_CPF_CNPJ_USE_CASE';
export const LIST_PRODUCER_BY_CPF_CNPJ_SERVICE = 'LIST_PRODUCER_BY_CPF_CNPJ_SERVICE';
// RURAL PROPERTY CONSTANTS
export const CREATE_RURAL_PROPERTY_USE_CASE = 'CREATE_RURAL_PROPERTY_USE_CASE';
export const CREATE_RURAL_PROPERTY_SERVICE = 'CREATE_RURAL_PROPERTY_SERVICE';
export const UPDATE_RURAL_PROPERTY_USE_CASE = 'UPDATE_RURAL_PROPERTY_USE_CASE';
export const UPDATE_RURAL_PROPERTY_SERVICE = 'UPDATE_RURAL_PROPERTY_SERVICE';
export const DELETE_RURAL_PROPERTY_USE_CASE = 'DELETE_RURAL_PROPERTY_USE_CASE';
export const DELETE_RURAL_PROPERTY_SERVICE = 'DELETE_RURAL_PROPERTY_SERVICE';
export const LIST_RURAL_PROPERTY_BY_PRODUCER_ID_USE_CASE = 'LIST_RURAL_PROPERTY_BY_PRODUCER_ID_USE_CASE';
export const LIST_RURAL_PROPERTY_BY_PRODUCER_ID_SERVICE = 'LIST_RURAL_PROPERTY_BY_PRODUCER_ID_SERVICE';
export const LIST_RURAL_PROPERTY_BY_ID_USE_CASE = 'LIST_RURAL_PROPERTY_BY_ID_USE_CASE';
export const LIST_RURAL_PROPERTY_BY_ID_SERVICE = 'LIST_RURAL_PROPERTY_BY_ID_SERVICE';
