export const DATABASE_CONNECTION_REPOSITORY = 'DATABASE_CONNECTION_REPOSITORY';
export const CREATE_PRODUCER_USE_CASE = 'CREATE_PRODUCER_USE_CASE';
export const CREATE_PRODUCER_SERVICE = 'CREATE_PRODUCER_SERVICE';
export const CREATE_PRODUCER_REPOSITORY = 'CREATE_PRODUCER_REPOSITORY';
